[package]
name = "rgb_rpc"
description = "RGB node RPC API"
version = "0.8.0-rc.2"
authors = ["Dr. Maxim Orlovsky <orlovsky@lnp-bp.org>"]
license = "MIT"
keywords = ["bitcoin", "node", "layer-2", "smart-contracts", "rgb"]
categories = ["network-programming"]
edition = "2021"
rust-version = "1.59.0"
readme = "../README.md"

[lib]
name = "rgb_rpc"

[dependencies]
amplify = "3.12.1"
strict_encoding = "~0.8.0"
rgb-std = { version = "0.8.0-rc.2", git = "https://github.com/RGB-WG/rgb-std" }
lnpbp = "0.8.0"
bitcoin = "0.28.1"
psbt = "0.8.0"
internet2 = "0.8.0"
microservices = { version = "0.8.0", default-features = false, features = ["client"] }
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
serde_with = { version = "1.8", optional = true }
serde_yaml = { version = "0.8.23", optional = true }
log = "0.4.14"
colored = "2"

[features]
default = ["serde"]
all = ["serde"]
serde = [
    "serde_crate", "serde_with", "serde_yaml", "rgb-std/serde",
    "amplify/serde", "internet2/serde", "microservices/serde",
]
