version: '3.2'

services:
  rgb-node-0:
    container_name: rgb-node-0
    image: rgb-node:0.4.0
    build: .
    entrypoint: "rgbd -vvvv"
    volumes:
      - ./samples:/var/lib/rgb/samples
      - data0:/var/lib/rgb
    working_dir: /var/lib/rgb
  rgb-node-1:
    container_name: rgb-node-1
    image: rgb-node:0.4.0
    build: .
    entrypoint: "rgbd -vvvv"
    volumes:
      - ./samples:/var/lib/rgb/samples
      - data1:/var/lib/rgb
    working_dir: /var/lib/rgb

volumes:
  data0:
  data1:

